# Generated by Django 5.0.6 on 2024-09-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_anouncement_created_anouncement_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anouncement',
            name='ar_body',
            field=models.TextField(default='علوم الحاسوب'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anouncement',
            name='ar_title',
            field=models.CharField(default='علوم الحاسوب', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='college',
            name='ar_description',
            field=models.TextField(default='علوم الحاسوب', verbose_name='College Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='college',
            name='ar_name',
            field=models.CharField(default='علوم الحاسوب', max_length=256, unique=True, verbose_name='College Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='college',
            name='batch',
            field=models.CharField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year'), (5, '5th Year')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
    ]
